[package]
name = "timing-wheel"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
name = "hierarchical_timing_wheel"
harness = false
